"use client";

import { useEffect, useState } from "react";

interface WateringCanProps {
  onComplete: () => void;
}

export default function WateringCan({ onComplete }: WateringCanProps) {
  useEffect(() => {
    const timer = setTimeout(onComplete, 2200); // 2s animation + buffer
    return () => clearTimeout(timer);
  }, [onComplete]);

  return (
    <div className="absolute -top-24 -right-16 z-50 pointer-events-none">
      <div className="relative w-32 h-32 animate-pour">
        {/* Water Stream */}
        <div className="absolute top-[65px] left-[5px] z-0">
           {/* Main Stream */}
          <div className="w-1.5 h-20 bg-blue-400/60 rounded-full animate-stream origin-top blur-[1px]" />
          
          {/* Droplets / Splash */}
          <div className="absolute top-16 -left-2 w-full flex justify-center">
             {/* Particles generated by CSS or simply mapped */}
             {[...Array(5)].map((_, i) => (
                <div 
                  key={i}
                  className="absolute w-1.5 h-1.5 bg-blue-300 rounded-full animate-drops opacity-0"
                  style={{ 
                    animationDelay: `${0.5 + i * 0.1}s`,
                    left: `${(i - 2) * 4}px`
                  }}
                />
             ))}
          </div>
        </div>

        {/* Can SVG */}
        <svg 
          viewBox="0 0 100 100" 
          className="w-full h-full drop-shadow-xl filter"
          style={{ transform: "rotate(10deg)" }}
        >
          <g>
            {/* Can Body */}
            <path 
              d="M30 30 L70 30 L75 80 L25 80 Z" 
              fill="#fbbf24" 
              stroke="#b45309" 
              strokeWidth="2"
              strokeLinejoin="round"
            />
            {/* Spout */}
            <path 
              d="M30 40 L10 45 L5 40" 
              fill="none" 
              stroke="#fbbf24" 
              strokeWidth="6" 
              strokeLinecap="round"
            />
            <circle cx="5" cy="40" r="3" fill="#fbbf24" stroke="#b45309" strokeWidth="1" />
            
            {/* Handle */}
            <path 
              d="M72 40 C 90 40, 90 70, 74 75" 
              fill="none" 
              stroke="#b45309" 
              strokeWidth="4" 
              strokeLinecap="round"
            />
            
            {/* Details */}
            <path d="M35 35 L65 35" stroke="#fff" strokeWidth="1" opacity="0.4" />
          </g>
        </svg>
      </div>
    </div>
  );
}